using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Disable warning CS8618 to suppress "Non-nullable field is uninitialized" compiler warning.
#pragma warning disable CS8618
// This class represents a Manufacturer entity in the database.
public class Manufacturer
{
    // Primary key for the Manufacturer entity, automatically generated by the database.
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ManufacturerId { get; set; }

    [Required(ErrorMessage = "Manufacturer name is required")]
    [MaxLength(100, ErrorMessage = "Manufacturer name cannot exceed 100 characters")]
    public string ManufacturerName { get; set; }
}
#pragma warning restore CS8618

