version: '3.7'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      # MSSQL_DB_NAME: "CovidDb"
    ports:
      - "1433:1433"
    # volumes:
    #   - ./Sql/:/docker-entrypoint-initdb.d/

  # covid-system:
  #   image: covid-system
  #   container_name: covid-system-api
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=CovidDb;User=sa;Password=YourStrong!Passw0rd
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - sql-server
