version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: covidSystemDb
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  covid-system:
    build: .
    container_name: covid-system-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=covidSystemDb;Uid=yourusername;Pwd=yourpassword;
    ports:
      - "5001:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
